# Generated by Django 5.0.7 on 2024-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
                ('image_url', models.URLField(blank=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('capital', 'Capital'), ('nation', 'Nation'), ('politics', 'Politics'), ('global', 'Global'), ('stock', 'Stock'), ('sports', 'Sports'), ('science_tech', 'Science & Tech'), ('weather', 'Weather')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
