# Generated by Django 5.0.7 on 2024-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
