# Generated by Django 5.0.7 on 2024-08-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_news', '0004_author_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
