# Generated by Django 5.0.7 on 2024-08-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_news', '0006_user_alter_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
